# The extension of files to be updated, adding support for conditional giter8 extensions
updates.fileExtensions = [".mill", ".sbt", ".sc", ".scala", ".sbt$endif$", ".mill$endif$", "mill-version", "mill-version$endif$", ".sc$endif$", ".scala$endif$"]
